# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16aa044b196c993c156fe899848ef5bfb7e263cd9910e8683266213ba870a6e87127d642f76d3e49de66887110bbd184dd92cd6266877ce5ad1cf24b3e09c02

test:
  secret_key_base: 6dabcd3bba7d5291386dbb72720eadf9991f183fd7612d69b15024bce39c30e8ca7c331aab1bd10ebf0b13f1fb795fcb97784843cc5cf035db772eb1a388a85c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
